# Generated by Django 5.2.10 on 2026-02-05 06:20

from django.db import migrations



def add_manufacturers(apps, schema_editor):
    Manufacturer = apps.get_model('cars', 'Manufacturer')
    manufacturers_data = [
        {"name": "Maruti Suzuki", "country": "India"},
        {"name": "Hyundai", "country": "South Korea"},
        {"name": "Tata Motors", "country": "India"},
        {"name": "Mahindra", "country": "India"},
        {"name": "Honda", "country": "Japan"},
        {"name": "Toyota", "country": "Japan"},
        {"name": "Kia", "country": "South Korea"},
        {"name": "Volkswagen", "country": "Germany"},
        {"name": "Renault", "country": "France"},
        {"name": "Nissan", "country": "Japan"},
        {"name": "Ford", "country": "USA"},
        {"name": "Skoda", "country": "Czech Republic"},
        {"name": "MG Motor", "country": "UK"},
        {"name": "Jeep", "country": "USA"},
    ]
    for data in manufacturers_data:
        Manufacturer.objects.get_or_create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_manufacturers),
    ]
